// BIOMD0000000007 ( 2025-08-01 16:03:19 )

diagram = [
{ data: { id: 'Cdc2 phosphorylation_mod',},classes: 'mid'},
{ data: { id: 'Cdc13_Cdc2',label: 'Cdc13_Cdc2'}},
{ data: { id: 'ubiquitinProtease2',label: 'ubiquitinProtease2'}},
{ data: { id: 'Cdc13 degradation in Cdc13_P-Cdc2_mod',},classes: 'mid'},
{ data: { id: 'BoundWee1',label: 'BoundWee1'}},
{ data: { id: 'Cdc13 degradation in Cdc13_Cdc2_mod',},classes: 'mid'},
{ data: { id: 'Cdc13_Cdc2_Rum1',label: 'Cdc13_Cdc2_Rum1'}},
{ data: { id: 'Cig2_Cdc2_Rum1',label: 'Cig2_Cdc2_Rum1'}},
{ data: { id: 'FreeRum1_deg',label: 'FreeRum1_deg'}, classes: 'deg'},
{ data: { id: 'Cdc13_Cdc2_src',label: 'Cdc13_Cdc2_src'}, classes: 'src'},
{ data: { id: 'Cdc13_P-Cdc2_deg',label: 'Cdc13_P-Cdc2_deg'}, classes: 'deg'},
{ data: { id: 'Cdc25',label: 'Cdc25'}},
{ data: { id: 'ubiquitinProtease1',label: 'ubiquitinProtease1'}},
{ data: { id: 'Cig2 degradation in Cig2_Cdc2_mod',},classes: 'mid'},
{ data: { id: 'Cig2_Cdc2_deg',label: 'Cig2_Cdc2_deg'}, classes: 'deg'},
{ data: { id: 'IntermediaryEnzyme',label: 'IntermediaryEnzyme'}},
{ data: { id: 'M-phasePromotingFactor',label: 'M-phasePromotingFactor'}},
{ data: { id: 'UbE production & degradation_mod',},classes: 'mid'},
{ data: { id: 'UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_Cdc2_mod',},classes: 'mid'},
{ data: { id: 'binding of Rum1 with Cdc13_P-Cdc2_mod',},classes: 'mid'},
{ data: { id: 'FreeRum1_src',label: 'FreeRum1_src'}, classes: 'src'},
{ data: { id: 'BoundCdc25',label: 'BoundCdc25'}},
{ data: { id: 'Wee1',label: 'Wee1'}},
{ data: { id: 'S-phasePromotingFactor',label: 'S-phasePromotingFactor'}},
{ data: { id: 'UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_P-Cdc2_mod',},classes: 'mid'},
{ data: { id: 'UbE2 production & degradation_mod',},classes: 'mid'},
{ data: { id: 'binding of Rum1 with Cdc13_Cdc2_mod',},classes: 'mid'},
{ data: { id: 'FreeRum1',label: 'FreeRum1'}},
{ data: { id: 'Cdc13_P-Cdc2_Rum1',label: 'Cdc13_P-Cdc2_Rum1'}},
{ data: { id: 'IE production & degradation_mod',},classes: 'mid'},
{ data: { id: 'Cdc25 production & degradation_mod',},classes: 'mid'},
{ data: { id: 'Binding of Rum1 to Cig2_Cdc2_mod',},classes: 'mid'},
{ data: { id: 'Rum1 degradation by SPF_mod',},classes: 'mid'},
{ data: { id: 'BoundIntermediaryEnzyme',label: 'BoundIntermediaryEnzyme'}},
{ data: { id: 'Wee1 production & degradation_mod',},classes: 'mid'},
{ data: { id: 'Cig2_Cdc2_src',label: 'Cig2_Cdc2_src'}, classes: 'src'},
{ data: { id: 'BoundUbiquitinProtease1',label: 'BoundUbiquitinProtease1'}},
{ data: { id: 'Cdc13_P-Cdc2',label: 'Cdc13_P-Cdc2'}},
{ data: { id: 'BoundUbiquitinProtease2',label: 'BoundUbiquitinProtease2'}},
{ data: { id: 'Cig2_Cdc2',label: 'Cig2_Cdc2'}},
{ data: { id: 'Cdc13_Cdc2_deg',label: 'Cdc13_Cdc2_deg'}, classes: 'deg'},
{ data: { id: 'r0',source: 'Cdc13_Cdc2_src',target: 'Cdc13_Cdc2',tcID: '(Cdc13_Cdc2 creation).Flux',label: 'k/C'}, classes: 'reaction'},
{ data: { id: 'r1',source: 'Cig2_Cdc2_src',target: 'Cig2_Cdc2',tcID: '(Cig2_Cdc2 creation).Flux',label: 'k/C'}, classes: 'reaction'},
{ data: { id: 'r2',source: 'Cdc13_Cdc2',target: 'Cdc2 phosphorylation_mod',tcID: '(Cdc2 phosphorylation).Flux',label: '(C*C*k-k*(C*C))/C'}, classes: 'reaction'},
{ data: { id: 'r3',source: 'Cdc2 phosphorylation_mod',target: 'Cdc13_P-Cdc2',tcID: '(Cdc2 phosphorylation).Flux',label: '(C*C*k-k*(C*C))/C'}, classes: 'reaction'},
{ data: { id: 'r4',source: 'Wee1',target: 'Cdc2 phosphorylation_mod',tcID: 'Wee1',label: '(C*C*k-k*(C*C))/C'}, classes: 'mod'},
{ data: { id: 'r5',source: 'Cdc25',target: 'Cdc2 phosphorylation_mod',tcID: 'Cdc25',label: '(C*C*k-k*(C*C))/C'}, classes: 'mod'},
{ data: { id: 'r6',source: 'Cdc13_Cdc2',target: 'binding of Rum1 with Cdc13_Cdc2_mod',tcID: '(binding of Rum1 with Cdc13_Cdc2).Flux',label: '(C*C*k*(F*C)-C*C*kr)/C'}, classes: 'reaction'},
{ data: { id: 'r7',source: 'FreeRum1',target: 'binding of Rum1 with Cdc13_Cdc2_mod',tcID: '(binding of Rum1 with Cdc13_Cdc2).Flux',label: '(C*C*k*(F*C)-C*C*kr)/C'}, classes: 'reaction'},
{ data: { id: 'r8',source: 'binding of Rum1 with Cdc13_Cdc2_mod',target: 'Cdc13_Cdc2_Rum1',tcID: '(binding of Rum1 with Cdc13_Cdc2).Flux',label: '(C*C*k*(F*C)-C*C*kr)/C'}, classes: 'reaction'},
{ data: { id: 'r9',source: 'Cdc13_P-Cdc2',target: 'binding of Rum1 with Cdc13_P-Cdc2_mod',tcID: '(binding of Rum1 with Cdc13_P-Cdc2).Flux',label: '(k*(C*C)*(F*C)-kr*(CF*C))/C'}, classes: 'reaction'},
{ data: { id: 'r10',source: 'FreeRum1',target: 'binding of Rum1 with Cdc13_P-Cdc2_mod',tcID: '(binding of Rum1 with Cdc13_P-Cdc2).Flux',label: '(k*(C*C)*(F*C)-kr*(CF*C))/C'}, classes: 'reaction'},
{ data: { id: 'r11',source: 'binding of Rum1 with Cdc13_P-Cdc2_mod',target: 'Cdc13_P-Cdc2_Rum1',tcID: '(binding of Rum1 with Cdc13_P-Cdc2).Flux',label: '(k*(C*C)*(F*C)-kr*(CF*C))/C'}, classes: 'reaction'},
{ data: { id: 'r12',source: 'Cdc13_Cdc2_Rum1',target: 'Cdc13_Cdc2',tcID: '(Rum1 degradation in Rum1_Cdc13_Cdc2).Flux',label: 'k*C'}, classes: 'reaction'},
{ data: { id: 'r13',source: 'FreeRum1',target: 'FreeRum1_deg',tcID: '(Rum1 degradation in solution).Flux',label: 'k*F'}, classes: 'reaction'},
{ data: { id: 'r14',source: 'Cdc13_P-Cdc2_Rum1',target: 'Cdc13_P-Cdc2',tcID: '(Rum1 degradation in Rum1_Cdc13_P-Cdc2).Flux',label: 'k*C'}, classes: 'reaction'},
{ data: { id: 'r15',source: 'Cig2_Cdc2_Rum1',target: 'Cig2_Cdc2',tcID: '(Rum1 degradation in Rum1_Cig2_Cdc2).Flux',label: 'k*C'}, classes: 'reaction'},
{ data: { id: 'r16',source: 'Cdc13_Cdc2',target: 'Cdc13 degradation in Cdc13_Cdc2_mod',tcID: '(Cdc13 degradation in Cdc13_Cdc2).Flux',label: 'k*C'}, classes: 'reaction'},
{ data: { id: 'r17',source: 'Cdc13 degradation in Cdc13_Cdc2_mod',target: 'Cdc13_Cdc2_deg',tcID: '(Cdc13 degradation in Cdc13_Cdc2).Flux',label: 'k*C'}, classes: 'reaction'},
{ data: { id: 'r18',source: 'ubiquitinProtease1',target: 'Cdc13 degradation in Cdc13_Cdc2_mod',tcID: 'ubiquitinProtease1',label: 'k*C'}, classes: 'mod'},
{ data: { id: 'r19',source: 'Cdc13_P-Cdc2',target: 'Cdc13 degradation in Cdc13_P-Cdc2_mod',tcID: '(Cdc13 degradation in Cdc13_P-Cdc2).Flux',label: 'k*C'}, classes: 'reaction'},
{ data: { id: 'r20',source: 'Cdc13 degradation in Cdc13_P-Cdc2_mod',target: 'Cdc13_P-Cdc2_deg',tcID: '(Cdc13 degradation in Cdc13_P-Cdc2).Flux',label: 'k*C'}, classes: 'reaction'},
{ data: { id: 'r21',source: 'ubiquitinProtease1',target: 'Cdc13 degradation in Cdc13_P-Cdc2_mod',tcID: 'ubiquitinProtease1',label: 'k*C'}, classes: 'mod'},
{ data: { id: 'r22',source: 'Cig2_Cdc2',target: 'Cig2 degradation in Cig2_Cdc2_mod',tcID: '(Cig2 degradation in Cig2_Cdc2).Flux',label: 'k*C'}, classes: 'reaction'},
{ data: { id: 'r23',source: 'Cig2 degradation in Cig2_Cdc2_mod',target: 'Cig2_Cdc2_deg',tcID: '(Cig2 degradation in Cig2_Cdc2).Flux',label: 'k*C'}, classes: 'reaction'},
{ data: { id: 'r24',source: 'ubiquitinProtease2',target: 'Cig2 degradation in Cig2_Cdc2_mod',tcID: 'ubiquitinProtease2',label: 'k*C'}, classes: 'mod'},
{ data: { id: 'r25',source: 'Cdc13_P-Cdc2_Rum1',target: 'FreeRum1',tcID: '(Cdc13 degradation in Rum1_Cdc13_P-Cdc2).Flux',label: 'k*C'}, classes: 'reaction'},
{ data: { id: 'r26',source: 'Cdc13_Cdc2_Rum1',target: 'FreeRum1',tcID: '(Cdc13 degradation in Rum1_Cdc13_Cdc2).Flux',label: 'k*C'}, classes: 'reaction'},
{ data: { id: 'r27',source: 'Cig2_Cdc2_Rum1',target: 'FreeRum1',tcID: '(Cig2 degradation in Rum1_Cig2_Cdc2).Flux',label: 'k*C'}, classes: 'reaction'},
{ data: { id: 'r28',source: 'Cig2_Cdc2',target: 'Binding of Rum1 to Cig2_Cdc2_mod',tcID: '(Binding of Rum1 to Cig2_Cdc2).Flux',label: '(C*C*k*(F*C)-C*C*kr)/C'}, classes: 'reaction'},
{ data: { id: 'r29',source: 'FreeRum1',target: 'Binding of Rum1 to Cig2_Cdc2_mod',tcID: '(Binding of Rum1 to Cig2_Cdc2).Flux',label: '(C*C*k*(F*C)-C*C*kr)/C'}, classes: 'reaction'},
{ data: { id: 'r30',source: 'Binding of Rum1 to Cig2_Cdc2_mod',target: 'Cig2_Cdc2_Rum1',tcID: '(Binding of Rum1 to Cig2_Cdc2).Flux',label: '(C*C*k*(F*C)-C*C*kr)/C'}, classes: 'reaction'},
{ data: { id: 'r31',source: 'Cdc13_Cdc2_Rum1',target: 'UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_Cdc2_mod',tcID: '(UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_Cdc2).Flux',label: 'k*C'}, classes: 'reaction'},
{ data: { id: 'r32',source: 'UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_Cdc2_mod',target: 'FreeRum1',tcID: '(UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_Cdc2).Flux',label: 'k*C'}, classes: 'reaction'},
{ data: { id: 'r33',source: 'ubiquitinProtease1',target: 'UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_Cdc2_mod',tcID: 'ubiquitinProtease1',label: 'k*C'}, classes: 'mod'},
{ data: { id: 'r34',source: 'Cdc13_P-Cdc2_Rum1',target: 'UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_P-Cdc2_mod',tcID: '(UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_P-Cdc2).Flux',label: 'k*C'}, classes: 'reaction'},
{ data: { id: 'r35',source: 'UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_P-Cdc2_mod',target: 'FreeRum1',tcID: '(UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_P-Cdc2).Flux',label: 'k*C'}, classes: 'reaction'},
{ data: { id: 'r36',source: 'ubiquitinProtease1',target: 'UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_P-Cdc2_mod',tcID: 'ubiquitinProtease1',label: 'k*C'}, classes: 'mod'},
{ data: { id: 'r37',source: 'FreeRum1_src',target: 'FreeRum1',tcID: '(Rum1 creation).Flux',label: 'k/C'}, classes: 'reaction'},
{ data: { id: 'r38',source: 'FreeRum1',target: 'Rum1 degradation by SPF_mod',tcID: '(Rum1 degradation by SPF).Flux',label: 'k*M*F*(S*C)/(K+F*C)'}, classes: 'reaction'},
{ data: { id: 'r39',source: 'Rum1 degradation by SPF_mod',target: 'FreeRum1_deg',tcID: '(Rum1 degradation by SPF).Flux',label: 'k*M*F*(S*C)/(K+F*C)'}, classes: 'reaction'},
{ data: { id: 'r40',source: 'S-phasePromotingFactor',target: 'Rum1 degradation by SPF_mod',tcID: 'S-phasePromotingFactor',label: 'k*M*F*(S*C)/(K+F*C)'}, classes: 'mod'},
{ data: { id: 'r41',source: 'BoundIntermediaryEnzyme',target: 'IE production & degradation_mod',tcID: '(IE production & degradation).Flux',label: '(IB*C*k*(M*C)/(IB*C+K)-I*C*kr/(I*C+Kr))/C'}, classes: 'reaction'},
{ data: { id: 'r42',source: 'IE production & degradation_mod',target: 'IntermediaryEnzyme',tcID: '(IE production & degradation).Flux',label: '(IB*C*k*(M*C)/(IB*C+K)-I*C*kr/(I*C+Kr))/C'}, classes: 'reaction'},
{ data: { id: 'r43',source: 'M-phasePromotingFactor',target: 'IE production & degradation_mod',tcID: 'M-phasePromotingFactor',label: '(IB*C*k*(M*C)/(IB*C+K)-I*C*kr/(I*C+Kr))/C'}, classes: 'mod'},
{ data: { id: 'r44',source: 'BoundUbiquitinProtease1',target: 'UbE production & degradation_mod',tcID: '(UbE production & degradation).Flux',label: '(I*C*k*(uB*C)/(K+uB*C)-kr*(u*C)/(Kr+u*C))/C'}, classes: 'reaction'},
{ data: { id: 'r45',source: 'UbE production & degradation_mod',target: 'ubiquitinProtease1',tcID: '(UbE production & degradation).Flux',label: '(I*C*k*(uB*C)/(K+uB*C)-kr*(u*C)/(Kr+u*C))/C'}, classes: 'reaction'},
{ data: { id: 'r46',source: 'IntermediaryEnzyme',target: 'UbE production & degradation_mod',tcID: 'IntermediaryEnzyme',label: '(I*C*k*(uB*C)/(K+uB*C)-kr*(u*C)/(Kr+u*C))/C'}, classes: 'mod'},
{ data: { id: 'r47',source: 'BoundUbiquitinProtease2',target: 'UbE2 production & degradation_mod',tcID: '(UbE2 production & degradation).Flux',label: '(k*(M*C)*(uB*C)/(K+uB*C)-k*(u*C)/(K+u*C))/C'}, classes: 'reaction'},
{ data: { id: 'r48',source: 'UbE2 production & degradation_mod',target: 'ubiquitinProtease2',tcID: '(UbE2 production & degradation).Flux',label: '(k*(M*C)*(uB*C)/(K+uB*C)-k*(u*C)/(K+u*C))/C'}, classes: 'reaction'},
{ data: { id: 'r49',source: 'M-phasePromotingFactor',target: 'UbE2 production & degradation_mod',tcID: 'M-phasePromotingFactor',label: '(k*(M*C)*(uB*C)/(K+uB*C)-k*(u*C)/(K+u*C))/C'}, classes: 'mod'},
{ data: { id: 'r50',source: 'BoundWee1',target: 'Wee1 production & degradation_mod',tcID: '(Wee1 production & degradation).Flux',label: '(kr*(WB*C)/(Kr+WB*C)-k*(M*C)*(W*C)/(K+W*C))/C'}, classes: 'reaction'},
{ data: { id: 'r51',source: 'Wee1 production & degradation_mod',target: 'Wee1',tcID: '(Wee1 production & degradation).Flux',label: '(kr*(WB*C)/(Kr+WB*C)-k*(M*C)*(W*C)/(K+W*C))/C'}, classes: 'reaction'},
{ data: { id: 'r52',source: 'M-phasePromotingFactor',target: 'Wee1 production & degradation_mod',tcID: 'M-phasePromotingFactor',label: '(kr*(WB*C)/(Kr+WB*C)-k*(M*C)*(W*C)/(K+W*C))/C'}, classes: 'mod'},
{ data: { id: 'r53',source: 'BoundCdc25',target: 'Cdc25 production & degradation_mod',tcID: '(Cdc25 production & degradation).Flux',label: '(CB*C*k*(M*C)/(CB*C+K)-C*C*kr/(C*C+Kr))/C'}, classes: 'reaction'},
{ data: { id: 'r54',source: 'Cdc25 production & degradation_mod',target: 'Cdc25',tcID: '(Cdc25 production & degradation).Flux',label: '(CB*C*k*(M*C)/(CB*C+K)-C*C*kr/(C*C+Kr))/C'}, classes: 'reaction'},
{ data: { id: 'r55',source: 'M-phasePromotingFactor',target: 'Cdc25 production & degradation_mod',tcID: 'M-phasePromotingFactor',label: '(CB*C*k*(M*C)/(CB*C+K)-C*C*kr/(C*C+Kr))/C'}, classes: 'mod'}
];
